app/urls.py
urlpatterns = []

app/models.py
# coding: utf-8
from django.db import models


class Translation(models.Model):
    """
    source:
    target:
    sourceLocale:
    targetLocale:
    """
    source = models.CharField(max_length=255, unique=True)
    target = models.CharField(max_length=255)

    createdAt = models.DateTimeField(auto_now_add=True)

    sourceLocale = models.CharField(max_length=25)
    targetLocale = models.CharField(max_length=25)

    class Meta(object):
        pass

    @property
    def simple(self):
        return [self.source, self.target]

    def __unicode__(self):
        return u"{0}: {1}".format(self.source, self.target)


class GrammaticalClass(models.Model):
    """
    name:
    words:
    """
    name = models.CharField(max_length=255)
    translation = models.ForeignKey("Translation")

    def __unicode__(self):
        return self.name


class Word(models.Model):
    """
    word:
    """
    name = models.CharField(max_length=255)
    grammaticalClass = models.ForeignKey("GrammaticalClass")
    reversewords = models.ManyToManyField("ReverseWord")

    def __unicode__(self):
        return self.name


class ReverseWord(models.Model):
    """
    reverse:
    """
    name = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name

db/models.py
# coding: utf-8
from django.db import models


class Translation(models.Model):
    """
    source:
    target:
    sourceLocale:
    targetLocale:
    """
    source = models.CharField(max_length=255, unique=True)
    target = models.CharField(max_length=255)

    createdAt = models.DateTimeField(auto_now_add=True)

    sourceLocale = models.CharField(max_length=25)
    targetLocale = models.CharField(max_length=25)

    class Meta(object):
        app_label = "db"

    @property
    def simple(self):
        return [self.source, self.target]

    def __unicode__(self):
        return u"{0}: {1}".format(self.source, self.target)


class GrammaticalClass(models.Model):
    """
    name:
    words:
    """
    name = models.CharField(max_length=255)
    translation = models.ForeignKey("Translation")

    def __unicode__(self):
        return self.name


class Word(models.Model):
    """
    word:
    """
    name = models.CharField(max_length=255)
    grammaticalClass = models.ForeignKey("GrammaticalClass")
    reversewords = models.ManyToManyField("ReverseWord")

    def __unicode__(self):
        return self.name


class ReverseWord(models.Model):
    """
    reverse:
    """
    name = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name

templates/translation.html
<html>
<head>
    <style type="text/css">
        #gm_cls {
            color: blue;
        }

        .gm_cls_group {
            background-color: antiquewhite;
            border-bottom-color: red;
        }

        #top-box {
            background-color: blanchedalmond;
        }

        h2 {
            text-align: center;
        }

        #dtl_word {
            background-color: aliceblue;
        }
    </style>
</head>

<div id="top-box">
    <h2>{{ queryset.source }} - {{ queryset.target }}</h2>
</div>
<hr>

{% for grammaticalclass in queryset.grammaticalclass_set.all %}
    <div class="gm_cls_group">
        <h3 id="gm_cls">{{ grammaticalclass.name }}</h3>
        <ul>
            {% for word in grammaticalclass.word_set.all %}
                <li>
                    <a href="#{{ word.name }}">{{ word.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% for word in grammaticalclass.word_set.all %}
        <div id="{{ word.name }}">
            <strong id="dtl_word">{{ word.name }}: </strong>

            <i>
                {% for reverseword in word.reversewords.all %}
                    {{ reverseword.name }};
                {% endfor %}
            </i>
        </div>
    {% endfor %}
{% endfor %}
</html>